version: "3.2"

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
        container_name: elastic_dkc
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - "discovery.type=single-node"
            - "ELASTIC_PASSWORD=macdinh"
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - ./manual/certs:/usr/share/elasticsearch/config/certs
            - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./manual/users:/usr/share/elasticsearch/config/users
            - ./manual/users_roles:/usr/share/elasticsearch/config/users_roles